// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"aurora/blog/api/app/service/manager/internal/biz"
	"aurora/blog/api/app/service/manager/internal/conf"
	"aurora/blog/api/app/service/manager/internal/data"
	"aurora/blog/api/app/service/manager/internal/server"
	"aurora/blog/api/app/service/manager/internal/service"
	"aurora/blog/api/pkg/lifecycle"
)

// Injectors from wire.go:

func initApp() (*lifecycle.App, func(), error) {
	logger := conf.NewZapLogger()
	configData := conf.NewDataConfig()
	dataData, cleanup, err := data.NewData(logger, configData)
	if err != nil {
		return nil, nil, err
	}
	repo := data.NewHelloRepo(dataData, logger)
	bizBiz := biz.NewBiz(repo)
	helloService := service.NewHelloService(bizBiz)
	engine := server.NewHttpRouter(helloService, logger)
	configServer := conf.NewServerConfig()
	transportServer := server.NewHttpServer(engine, logger, configServer)
	app := newApp(transportServer, logger)
	return app, func() {
		cleanup()
	}, nil
}
