// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Theme is the predicate function for theme builders.
type Theme func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
